# Generated by Django 2.0.6 on 2018-06-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0003_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(upload_to='static/res/', verbose_name='pic'),
        ),
    ]
