# Generated by Django 2.0.6 on 2018-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0005_auto_20180620_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='thumb',
            field=models.ImageField(default='thumbs/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='cat',
            field=models.CharField(choices=[('STUD', 'Study'), ('TECH', 'Technology'), ('LIFE', 'Lifestyle'), ('SPOR', 'Sports'), ('NEWS', 'News'), ('GAME', 'Gaming')], default='TECH', help_text='Enter a category', max_length=20),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(default='images/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='keywords',
            field=models.CharField(help_text='Enter a keywords', max_length=4),
        ),
    ]
