# Generated by Django 2.0.6 on 2018-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0007_auto_20180621_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postp',
        ),
        migrations.AlterField(
            model_name='newpost',
            name='cat',
            field=models.CharField(choices=[('Study', 'Study'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Sports', 'Sports'), ('News', 'News'), ('Gaming', 'Gaming')], default='Technology', help_text='Enter a category', max_length=20),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='keywords',
            field=models.CharField(help_text='Enter a keywords', max_length=40),
        ),
    ]
