# Generated by Django 2.0.6 on 2018-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0008_auto_20180621_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='cat',
            field=models.CharField(choices=[('Study', 'Study'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Sports', 'Sports'), ('News', 'News'), ('Gaming', 'Gaming'), ('Other', 'Other')], default='Technology', help_text='Enter a category', max_length=20),
        ),
    ]
