# Generated by Django 2.0.6 on 2018-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0014_auto_20180624_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
