# Generated by Django 2.0.6 on 2018-06-24 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0018_auto_20180624_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 18, 43, 28, 263522)),
        ),
    ]
