# Generated by Django 2.0.6 on 2018-06-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0019_auto_20180624_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
