# Generated by Django 2.0.6 on 2018-06-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0022_auto_20180624_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
