# Generated by Django 2.0.6 on 2018-06-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0002_auto_20180613_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cat', models.CharField(help_text='Enter a category', max_length=255)),
                ('keywords', models.CharField(help_text='Enter a keywords', max_length=255)),
                ('author', models.CharField(help_text='Enter author name', max_length=255)),
                ('image', models.ImageField(help_text='Upload Image here', upload_to='')),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
