# Generated by Django 2.0.6 on 2018-06-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0003_newpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='newpost',
            name='thumb',
            field=models.ImageField(default='thumbs/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='author',
            field=models.CharField(help_text='Enter author name', max_length=30),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='cat',
            field=models.CharField(choices=[('Study', 'Study'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Sports', 'Sports'), ('News', 'News'), ('Gaming', 'Gaming'), ('Other', 'Other')], default='Technology', help_text='Enter a category', max_length=20),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(default='images/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='keywords',
            field=models.CharField(help_text='Enter a keywords', max_length=40),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='smallthings.NewPost'),
        ),
    ]
