# Generated by Django 2.0.6 on 2018-06-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallthings', '0004_auto_20180624_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated',
        ),
    ]
